server:
  port: 8080

spring:
#  sql多数据源配置
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#mongoDB多数据源配置
  data:
    mongodb:
      rate:
        host: localhost
        port: 27017
        database: TRANSFER_RATE
#       username: admin
#       password: root123
#      uthenticationDatabase: admin

mybatis:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity

#mongoDB数据库
MTC: UPLOAD_MTCFEE

ftpRootPath: /var/ftp